# Site settings
author: Chris
title: Chris's Blog
header-img: img/home-bg.png
email: chrismetzgr@gmail.com
copyright_name: Chris
description: > # this means to ignore newlines until "baseurl:"
  A Blog Chris Wrote
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  critsmet

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
